# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('contacto_name', models.CharField(max_length=45)),
                ('contacto_nacimiento', models.DateField()),
                ('contacto_sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=50)),
                ('contacto_estado_civil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=50, verbose_name='Estado Civil')),
                ('contacto_email', models.CharField(max_length=50)),
                ('contacto_favorito', models.BooleanField(verbose_name='Favorito')),
            ],
        ),
    ]
