# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_name', models.CharField(max_length=120)),
                ('tarea_data_inicio', models.DateField()),
                ('concluido', models.BooleanField(verbose_name='Concluido')),
            ],
        ),
    ]
