# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_name', models.CharField(max_length=50)),
                ('cuenta_data_vencimiento', models.DateField()),
                ('pago', models.BooleanField(verbose_name='Pago')),
            ],
        ),
    ]
