# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_cuenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='tarea_name',
            new_name='tarea_nombre',
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_de_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
