# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0004_auto_20160520_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_de_creacion',
        ),
    ]
